### PR TITLE
Fixed up project and fixed up login issues, updated submodules

### PR DESCRIPTION
**Pull request by EvoPulseGaming**

### CODE REVIEW

**Comment by EvoPulseGaming** [comment]
NPlot was only binary, I added it as a submodule
SMS Verify was implemented
RobinhoodNet was updated for SMS_Verify and I cherry picked a few commits
Fixed an issue where account would not show balance.

Overall, I see there is way more functionality than what I see on the screen. I highly suspect there are local changes on your end that have not made it to the repo.

**Comment by EvoPulseGaming** [comment]
Nice. I hope the conflicts didn't give you too much trouble

**Comment by EvoPulseGaming** [comment]
I notice the RH.Net submodule points to an older commit.

**Comment by Terohnon** [comment]
Not too bad. I did decide to pull back in my binary reference to NPlot though, since like I said I have some custom modifications to it. At some point I hope to put those into a fork, but don't want to take the time right now. 

Sorry for taking so long to get to this. I'll try to be more responsive to any future pull requests.

**Comment by Terohnon** [comment]
Hmm, honestly I just did the merge through the GitHub page, pulling in any changes you suggested. If you want to update the submodule reference to a desired commit I'll pull that in.

**Comment by EvoPulseGaming** [comment]
It appears I have to fix something with the login part. I'll fix it and submit a pull request

**Pull request merged**
